### ISSUE TITLE
Please add xserver-xorg-input-synaptics package for touchpad to work be default

### ISSUE THREAD

**Issue by ghost** [Kanola-Images/Kanola#8]
### Issue Description

Tap to click option is grayed out and disabled in Touchpad settings until user manually installs `abroot pkg add xserver-xorg-input-synaptics`  and on rebooting option becomes available

### Steps to Reproduce

Fresh install of kanola-images/plasma by modifying abroot.json file , and on startup you will see tap to click is not working making it cumbersome to even change settings on touchpads , 
It is enabled by default in gnome , this problem is common with debian+plasma

### On what version of Kanola does this happen?

Unreleased

### Additional Information

Even though installing that  package brings back option to enable tap to click , but a better solution would be to make tap to click enabled by default

**Comment by Maxwelldoug** [comment]
This package is supposed to be in our default 'base' build toolchain, I'll look into why it is not present.

**Comment by Maxwelldoug** [comment]
Alright, I've looked into it, and generally, I've found that the Synaptics driver is no longer recommended for use, and hasn't been for a good 2 and a half years now. It has been obsoleted by libinput.

As such, I believe your touchpad issue may be unrelated. Can you elaborate on what exactly is not working?
The following links may be relevant, but I cannot test them due to a lack of available laptops for testing.
https://askubuntu.com/questions/1179275/enable-tap-to-click-kubuntu
https://bbs.archlinux.org/viewtopic.php?id=257510
https://unix.stackexchange.com/questions/337008/activate-tap-to-click-on-touchpad

**Comment by Maxwelldoug** [comment]
Closing this as a stale issue. If anyone can reproduce it and provide more details, please create a new issue referencing this one.
